### ISSUE TITLE
Consensus.py for gappy MSA?

### ISSUE THREAD

**Issue by avilella** [jrjhealey/bioinfo-tools#3]
Is there a parameter or trick to make Consensus.py generate a consensus for relatively gappy MSAs?
https://bioinformatics.stackexchange.com/questions/19115/generate-consensus-protein-sequence-from-relatively-gappy-alignment

Thx

**Comment by jrjhealey** [comment]
Apologies for only just seeing this comment 18 months later! I don't do as much bioinformatics these days so check github much less often.

As you've probably guessed by now, there isn't really much of a 'trick' to the code, and I built it fairly quickly so there isn't much sophistication to how it handles gaps.`

I assume you were using the `dumb` consensus mode?
